### ISSUE TITLE
REPORT_AUDIO_STATUS: for TV volume

### ISSUE THREAD

**Issue by bains88** [jbree/homebridge-cec-accessory#3]
@jbree Thank you for this amazing work. Powering TV ON/OFF works great, that too in new samsung model (KS8000) when samsung changed some transmission formats.

I configured the accessories section to switch on/off tv volume by giving a different name to that accessory and changing device to 0 for volume as well. I only get timeout error on it. Any idea about this??

[TV Volume] Error: No REPORT_AUDIO_STATUS received after 1000ms
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:63:23)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by jbree** [comment]
@bains88, thanks for the support!

I can't say this definitively, but my understanding is that CEC mute commands only work with a dedicated receiver handling your audio. I probably should make this more prominent in the readme. Sorry about that!

**Comment by bains88** [comment]
got it. Thanks.
