### ISSUE TITLE
Samsung TV JU6400

### ISSUE THREAD

**Issue by ageorgios** [jbree/homebridge-cec-accessory#7]
On a Samsung TV the behaviour is odd
state tv:off homebridge:off -turnon-> tv:on homebridge:on 
state tv:on homebridge:on -turnoff-> tv:on homebridge:off 
state tv:on homebridge:off -turnon-> tv:off homebridge:on 

this works:
```
$ cec-client
standby 0 | on 0
```

also when using address 5 on the homebridge plugin my soundbar is not recognized
but standby 5 | on 5 work

Actually I think the behavior of setOn is inverted.

**Comment by ageorgios** [comment]
I resolved it by removing the -m monitor option and by making the timeout 3000ms

can you explain?

**Comment by jbree** [comment]
If you change the timeout to 3000ms, but leave the `-m` option, does that make it work? Also, did you resolve both the tv and the soundbar behavior? Re: soundbar, do you have it configured to control power or volume?

**Comment by ageorgios** [comment]
You are right I can leave the -m option and it still works

but my soundbar does not work:

```
  {
      "accessory": "cec",
      "address": 5,
      "name": "Soundbar",
      "type": "volume"
    }
```

```
Oct 12 18:31:02 rpi3 homebridge[1874]: [10/12/2017, 6:31:02 PM] [Soundbar] Error: No REPORT_AUDIO_STATUS received after 3000ms
Oct 12 18:31:02 rpi3 homebridge[1874]: at Timeout._onTimeout (/usr/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:67:23)
Oct 12 18:31:02 rpi3 homebridge[1874]: at ontimeout (timers.js:386:14)
Oct 12 18:31:02 rpi3 homebridge[1874]: at tryOnTimeout (timers.js:250:5)
Oct 12 18:31:02 rpi3 homebridge[1874]: at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by jbree** [comment]
What happens if you run cec-client and give the command
`tx e5:71`

This should request the audio status from your sound bar. The expected response from this is apparently not coming back.

**Comment by ageorgios** [comment]
```
tx e5:71
TRAFFIC: [            5874]	<< e5:71
WARNING: [            5935]	unhandled response received: opcode=71 initiator=1 destination=5 response=0
DEBUG:   [            6875]	command 'give audio status' timeout
waiting for input
TRAFFIC: [            7716]	>> 0f:82:00:00
DEBUG:   [            7716]	making TV (0) the active source
DEBUG:   [            7717]	>> TV (0) -> Broadcast (F): active source (82)
```

it seems it does not respond from  'give audio status'

it is a samsung soundbar

the vol commands and mute work though with cec-client

**Comment by ageorgios** [comment]
I soft rebooted the rpi and the homebridge plugin gets timeout even though cec-client works..

it seems the cec-library is very unstable.

**Comment by ageorgios** [comment]
I removed the -m option and it survives soft reboot

**Comment by suffe** [comment]
I got the same message, error: No REPORT_POWER_STATUS received.

But when I use CEC-client and send tx e5:71, I got this.

DEBUG:   [            1801]	<< requesting power status of 'TV' (0)
TRAFFIC: [            1801]	<< 15:47:43:45:43:54:65:73:74:65:72
TRAFFIC: [            1801]	<< 10:8f
TRAFFIC: [            2265]	>> 01:90:00
waiting for input
DEBUG:   [            2265]	TV (0): power status changed from 'unknown' to 'on'
DEBUG:   [            2265]	expected response received (90: report power status)
DEBUG:   [            2265]	>> TV (0) -> Recorder 1 (1): report power status (90)
TRAFFIC: [            2265]	<< e5:71

looks right for me, also I can turn my samsung tv on and off true the CEC-client.
